name: lasagna
dependencies:
 - python=3
# - pyqt=5
 - numpy
 - tifffile
 - pyqtgraph
 - pyyaml
 - sip
 - scikit-image
 - scipy
 - matplotlib
 - ipython
 - vtk
 - ipython
 - traitlets
 - pip
 - pip:
     - pynrrd
     - pyqt5
     - nibabel
channels:
 - conda-forge
