name: lasagna
dependencies:
 - python=3.11
 - pip
 - numpy
 - tifffile
 - pyqtgraph
 - pyyaml
 - sip
 - scikit-image
 - scipy
 - matplotlib
 - ipython
 - vtk
 - ipython
 - traitlets
 - pip
 - pip:
     - pynrrd
     - pyqt5==5.15.6
     - nibabel
channels:
 - conda-forge
